---
- name: Check F5 version
  hosts: bigips
  connection: local
  tasks:
    - bigip_command:
        commands: 
           - show running-config  
        server: 192.168.92.150
        password: Cisco@123
        user: admin
        validate_certs: no
      register: show_run
    - copy:
       content: "{{show_run.stdout[0] }}"
       dest: "/home/admin/Ansible/F5/CFGS/{{inventory_hostname}}.txt"
