---

- name: Create a VIP, pool and pool members
  hosts: all
  connection: local
  
  vars:
   provider:
    password: Cisco@123
    server: 192.168.92.150
    user: admin
    validate_certs: no
    server_port: 443
        
  tasks:
    - bigip_pool:
       provider: "{{ provider }}"
       lb_method: ratio-member
       name: web
       slow_ramp_time: 120
 
    - bigip_pool_member:
       provider: "{{ provider }}"
       description: "webserver {{ item.name }}"
       host: "{{ item.host }}"
       name: "{{ item.name }}"
       pool: web
       port: 80
      loop:
       - host: 10.10.10.10
         name: web01
       - host: 10.10.10.11
         name: web02
    - bigip_virtual_server:
       provider: "{{ provider }}"
       description: foo-vip
       destination: 172.16.10.108
       name: vip-1
       pool: web
       port: 80
       snat: Automap
       profiles:
        - http
        - clientssl
