---

- name: Create a VIP, pool and pool members
  hosts: all
  connection: local
  
  vars:
   provider:
    password: Cisco@123
    server: 192.168.92.150
    user: admin
    validate_certs: no
    server_port: 443
        
  tasks:
    - bigip_pool:
       provider: "{{ provider }}"
       lb_method: ratio-member
       name: test
       slow_ramp_time: 120
 
    - bigip_pool_member:
       provider: "{{ provider }}"
       host: "{{hostvars[item].ansible_host}}"
       name: "{{hostvars[item].inventory_hostname }}"
       pool: test
       port: 80
      loop: "{{groups['webservers']}}"
    - bigip_virtual_server:
       provider: "{{ provider }}"
       description: test-VIP
       destination: 101.57.110.10
       name: vip-2
       pool: test
       port: 80
       snat: Automap
       profiles:
        - http
        - clientssl
